#!/usr/bin/env python
# -*- coding: utf-8 -*-
import rospy
from std_msgs.msg import String, Bool
from interaccion.msg import pos_usuario, inf_personal_usuario, usuario
from interaccion.srv import multiply
import configclock
import os

def multiplyper2srv(x):
    rospy.wait_for_service('multiplicar')
    try:
        add_two_ints = rospy.ServiceProxy('multiplicar', multiply)
        resp1 = add_two_ints(x)
        return resp1.resultado
    except rospy.ServiceException, e:
        print "Service call failed: %s"%e
def sendtimer():
    if not configclock.sent_first_message:
        configclock.sent_first_message=True
        configclock.pubstart.publish(configclock.msgclock)
    else:
        configclock.pubreset.publish(configclock.msgclock)
def callback1(data):
    print("Name:\t"+data.inf_personal.first_name)
    print("Age :\t"+str(data.inf_personal.age))
    print("Speaks :")
    for lan in data.inf_personal.language:
        print(lan)
    print("At :\t"+str(data.posicion.x)+" / "+str(data.posicion.y)+" / "+str(data.posicion.z))
    print("Thinks : \n" +data.usuario)
    print("Service returns:")
    print(str(multiplyper2srv(data.inf_personal.age)))
    print("______________________")
    sendtimer()
    text= "This is a text to syntetize sintetizar"
    command = "espeak \"" + text +"\""
    os.system(str(command));
def callback2(data):
    if data.data:
        print("\nClock is still alive\n")

def screen():
    rospy.init_node('screen', anonymous=True)
    rospy.Subscriber("user_topic", usuario, callback1)
    rospy.Subscriber("still_alive", Bool, callback2)
    rospy.spin()
if __name__ == '__main__':
    screen()
