#!/usr/bin/env python
import rospy
from std_msgs.msg import String
from interaccion.msg import pos_usuario
from interaccion.msg import inf_personal_usuario
from interaccion.msg import usuario
import config


def callback1(data):
    rospy.loginfo(rospy.get_caller_id() + "I heard %s", data.data)
    config.sdmg.usuario=data.data
    config.be=True
    data_ready()
def callback2(data):
    rospy.loginfo(rospy.get_caller_id() + "I heard %s", (data.first_name+str(data.age)+str(data.language)))
    config.sdmg.inf_personal=data
    config.bi=True
    data_ready()
def callback3(data):
    rospy.loginfo(rospy.get_caller_id() + "I heard %s", (data.x+data.y+data.z))
    config.sdmg.posicion=data
    config.bp=True
    data_ready()
def data_ready():
    if config.bi and config.bp and config.be:
        rospy.loginfo(rospy.get_caller_id() + "Sending valoration")
        config.pub.publish(config.sdmg)
        config.sdmg.usuario=None
        config.sdmg.posicion=None
        config.sdmg.inf_personal=None
        config.bi=False
        config.bp=False
        config.be=False

def listener():
    rospy.init_node('listener', anonymous=True)
    rospy.Subscriber("emocion_topic", String, callback1)
    rospy.Subscriber("inf_pers_topic", inf_personal_usuario, callback2)
    rospy.Subscriber("pos_usuario_topic", pos_usuario, callback3)
    # spin() simply keeps python from exiting until this node is stopped
    while not rospy.is_shutdown():
        rospy.spin()


if __name__ == '__main__':
    listener()
