#!/usr/bin/env python
# -*- coding: utf-8 -*-
import rospy
from std_msgs.msg import String
from ROSIntro.msg import pos_usuario
from ROSIntro.msg import inf_personal_usuario
from ROSIntro.msg import usuario
import config


def callback1(data):
    rospy.loginfo("\033[1;32;40m"+rospy.get_caller_id() +"\033[0m"+ " ha recibido una crítica %s","\033[1;36;40m"+str( data.data)+"\033[0m")
    config.sdmg.usuario=data.data
    config.be=True
    data_ready()
def callback2(data):
    rospy.loginfo("\033[1;32;40m"+rospy.get_caller_id() +"\033[0m"+  " ha recibido un usuario %s", ("\033[1;36;40m"+"nombre:"+data.first_name+" edad: "+str(data.age)+" idiomas:"+str(data.language)+"\033[0m"))
    config.sdmg.inf_personal=data
    config.bi=True
    data_ready()
def callback3(data):
    rospy.loginfo("\033[1;32;40m"+rospy.get_caller_id() +"\033[0m"+  " ha recibido una posicion %s", ("\033[1;36;40m"+"x: "+str(data.x)+" y:"+str(data.y)+" z:"+str(data.z)+"\033[0m"))
    config.sdmg.posicion=data
    config.bp=True
    data_ready()
def data_ready():
    if config.bi and config.bp and config.be:
        rospy.loginfo("\033[1;32;40m"+rospy.get_caller_id() +"\033[0m"+ ": "+"\033[1;36;40m"+ "Enviando valoracion"+"\033[0m")
        config.pub.publish(config.sdmg)
        config.sdmg.usuario=None
        config.sdmg.posicion=None
        config.sdmg.inf_personal=None
        config.bi=False
        config.bp=False
        config.be=False

def listener():
    rospy.init_node('listener', anonymous=True)
    rospy.loginfo("\033[1;32;40m"+rospy.get_caller_id() +"\033[0m"+" Inicio del empaquetador.")
    rospy.Subscriber("emocion_topic", String, callback1)
    rospy.Subscriber("inf_pers_topic", inf_personal_usuario, callback2)
    rospy.Subscriber("pos_usuario_topic", pos_usuario, callback3)
    # spin() simply keeps python from exiting until this node is stopped
    while not rospy.is_shutdown():
        rospy.spin()


if __name__ == '__main__':
    listener()
