#!/usr/bin/env python
# -*- coding: utf-8 -*-
# license removed for brevity
import rospy
from Tkinter import *
import tkMessageBox
import ScrolledText as sct
from ROSIntro.msg import inf_personal_usuario



def readtext(txt1,txt2,txtb,pub,rospy):
    #Funcion creada para enviar los datos del formulario al topico correspondiente
    try:
        a=txt1.get()
        b=int(txt2.get())
        c=txtb.get(1.0, END).upper().splitlines()
        try:
            while c.index(""):
               c.pop(c.index(""))
        except ValueError:
            pass

        hello_str=inf_personal_usuario()
        hello_str.first_name=a
        hello_str.age=b
        hello_str.language=c
        rospy.loginfo("\033[1;32;40m"+rospy.get_caller_id() +"\033[0m"+" envia: "+"\033[1;36;40m"+str(hello_str) +"\033[0m")
        pub.publish(hello_str)
        createMessBox("Success","Datos enviados.")
        txt1.delete('0', END)
        txt2.delete('0', END)
        txtb.delete('1.0', END)
    except:
        createMessBox("Error","Por favor compruebe los datos introducidos.")
    return [txt1,txt2,txtb]
def createMessBox(a,b):
    #funcion para la salida de error o success del envio de la informacion
    tkMessageBox.showinfo(a,b)
def talker():
    #main metodo de la aplicación para cumplir estandares
    #inicialización
    rospy.init_node('info', anonymous=True)
    rospy.loginfo("\033[1;32;40m"+rospy.get_caller_id() +"\033[0m"+" Inicio de la pantala de información personal.")
    pub = rospy.Publisher('inf_pers_topic', inf_personal_usuario, queue_size=10)
    rate = rospy.Rate(40) # 40hz
    window = Tk()
    window.title("Personal info app")
    label1=Label(text='Nombre:')
    label1.grid(column=0, row=0,padx=10, pady=10)
    txt1 = Entry(window,width="20")
    txt1.grid(column=1, row=0,padx=10, pady=10)
    label1=Label(text='Edad:')
    label1.grid(column=0, row=2,padx=10, pady=10)
    txt2 = Entry(window,width='20')
    txt2.grid(column=1, row=2,padx=10, pady=10)
    label1=Label(text='Idiomas:')
    label1.grid(column=0, row=4,padx=10, pady=10)
    txtb=sct.ScrolledText(height='10',width='20');
    #txtb.insert(INSERT,"I like trains")
    txtb.grid(column=1, row=4)
    btn = Button(window, text="Enviar", command= lambda:readtext(txt1,txt2,txtb,pub,rospy))
    btn.grid(column=1, row=6,padx=10, pady=10)

    #loop de la aplicación
    while not rospy.is_shutdown():
        try:
            #permite la modificación de la app sin bloquearla en el tk.mainloop
            window.update()
            window.update_idletasks()
            #para que el bucle no este constantemente se le pone una pequeña espera
            rate.sleep()
        except:
            break


if __name__ == '__main__':
    try:
        talker()
    except rospy.ROSInterruptException:
        pass
