#!/usr/bin/env python

from ROSIntro.srv import multiply
import rospy

def handle(req):
    rospy.loginfo("\033[1;32;40m"+rospy.get_caller_id() +"\033[0m"+ ": Se ha recibido: "+"\033[1;36;40m"+str(req)+"\033[0m")

    return (req.entrada*2)

def multiply_per_2():
    rospy.init_node('matematico_nodo')
    s = rospy.Service('multiplicar', multiply, handle)
    rospy.loginfo("\033[1;32;40m"+rospy.get_caller_id() +"\033[0m"+ ": Servicio matematico iniciado.")
    rospy.spin()

if __name__ == "__main__":
    multiply_per_2()
