#!/usr/bin/env python
# -*- coding: utf-8 -*-
# license removed for brevity

import roslib
import rospy
import actionlib

from interaccion.msg import *

if __name__ == '__main__':
    rospy.init_node('do_dishes_client')
    client = actionlib.SimpleActionClient('Printer_server', Actio1Action)

    client.wait_for_server(rospy.Duration(5))

    goal = Actio1Goal()
    goal.goal_msg="Scatman /n \n LALA"
    # Fill in the goal here
    client.send_goal(goal)
    print client.wait_for_result(rospy.Duration(5))
    if client.get_result():
     print client.get_result()
    else:
     print "Not reached"
