#!/usr/bin/env python
# -*- coding: utf-8 -*-
# license removed for brevity

import roslib
import rospy
import actionlib

from ROSIntro.msg import *

class Printer:
  def __init__(self):
    self.server = actionlib.SimpleActionServer('Printer_server', Actio1Action, self.execute, False)
    self.server.start()

  def execute(self, goal):
    rospy.loginfo("\033[1;32;40m"+rospy.get_caller_id() +"\033[0m"+" Comienza respuesta a peticion:"+"\033[1;36;40m"+goal.goal_msg+"\033[0m")
    f=open("Print.txt","a")
    a=Actio1Feedback()
    b=Actio1Result()
    r = rospy.Rate(1)
    cnt=1;
    quant=len(goal.goal_msg.splitlines())
    try:
        for i in goal.goal_msg.splitlines():
            a.line_printing="Imprimiendo:"+i
            a.percent_complete=100*cnt/quant
            self.server.publish_feedback(a)
            rospy.loginfo("\033[1;32;40m"+rospy.get_caller_id() +"\033[0m"+" Imprimiendo:"+"\033[1;36;40m"+i+"\033[0m")

            f.write(i+'\n')

            r.sleep()
            cnt=cnt+1
        # Do lots of awesome groundbreaking robot stuff here
        b.result_msg="Impresión correcta"
        b.result_bool=True
        f.close()
    except:
        b.result_msg="Error during print"
        b.result_bool=False
        f.close()
    self.server.set_succeeded(b)


if __name__ == '__main__':
  rospy.init_node('Printer_server')
  rospy.loginfo("\033[1;32;40m"+rospy.get_caller_id() +"\033[0m"+" Inicio del servicio de impresión.")
  server = Printer()
  rospy.spin()
